# Uncomment the next line to define a global platform for your project
platform :osx, '10.14'

target 'PPDownloader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PPDownloader

  pod 'CommandLine'
  pod 'MJExtension'
  pod 'MUFoundation/MUPath'
  
  pod 'AlfredKit'
  
end
